[project]
name = "startup-roast-bot"
cerebrium_url = "https://api.cerebrium.ai/v2"

[deployment]
name = "startup-roast-bot"
python_version = "3.11"
cuda = false
gpu = false
replicas = 1
min_replicas = 1
max_replicas = 10
response_grace_period = 180
timeout = 300
memory = "4Gi"
cpu = "2"

[cerebrium.runtime.custom]
port = 5000
entrypoint = "uvicorn app.main:app --host 0.0.0.0 --port 5000"
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"

[cerebrium.scaling]
replicas = 1
replica_concurrency = 1
response_grace_period = 180

[cerebrium.env]
BROWSERBASE_API_KEY = "env:BROWSERBASE_API_KEY"
BROWSERBASE_PROJECT_ID = "env:BROWSERBASE_PROJECT_ID"
GROK_API_KEY = "env:GROK_API_KEY"
GROK_MODEL = "env:GROK_MODEL"
S3_BUCKET = "env:S3_BUCKET"
AWS_ACCESS_KEY_ID = "env:AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY = "env:AWS_SECRET_ACCESS_KEY"
AWS_REGION = "env:AWS_REGION"

[build]
requirements = ["app/requirements.txt"]