[build]
runtime = "python3.11"

[cerebrium.runtime.custom]
port = 5000
entrypoint = "uvicorn app.main:app --host 0.0.0.0 --port 5000"
healthcheck_endpoint = "/health"
readycheck_endpoint = "/ready"

[cerebrium.scaling]
replicas = 1
replica_concurrency = 1
response_grace_period = 180

[cerebrium.env]
BROWSERBASE_API_KEY = "env:BROWSERBASE_API_KEY"
BROWSERBASE_PROJECT_ID = "env:BROWSERBASE_PROJECT_ID"
GROK_API_KEY = "env:GROK_API_KEY"
GROK_MODEL = "env:GROK_MODEL"
GROK_BASE_URL = "env:GROK_BASE_URL"